spring:
  application:
    name: activity-service

  datasource:
    username: postgres
    password: 19649072Sever
    url: jdbc:postgresql://localhost:5432/fitness_activity_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

